# Generated by Django 5.1 on 2025-06-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_fingerprint',
            field=models.TextField(blank=True, null=True, verbose_name='Устройство'),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Зарегистрированный IP'),
        ),
    ]
