# Generated by Django 5.1 on 2025-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_device_fingerprint_profile_registered_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
