# Generated by Django 5.1 on 2025-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
    ]
