# Generated by Django 5.1 on 2025-07-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_inn_alter_profile_ogrn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ogrn',
        ),
    ]
