# Generated by Django 5.1 on 2025-07-28 09:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(verbose_name='Логистическая услуга (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(verbose_name='Логистическая услуга (русский)')),
                ('email', models.EmailField(max_length=254)),
                ('tn_ved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТН ВЭД')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена')),
                ('price_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата цены')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('search_vector_product', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product')),
                ('search_vector_product_ru', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product_ru')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='SupplierDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(verbose_name='Продукция (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(verbose_name='Продукция (русский)')),
                ('email', models.EmailField(max_length=254)),
                ('tn_ved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТН ВЭД')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена')),
                ('price_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата цены')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('search_vector_product', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product')),
                ('search_vector_product_ru', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product_ru')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='TechnologyDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(verbose_name='Технология (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(verbose_name='Технология (русский)')),
                ('email', models.EmailField(max_length=254)),
                ('tn_ved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТН ВЭД')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена')),
                ('price_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата цены')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('search_vector_product', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product')),
                ('search_vector_product_ru', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product_ru')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.DeleteModel(
            name='SeoKey',
        ),
        migrations.AddIndex(
            model_name='logisticdemo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product'], name='primary_log_search__ea334f_gin'),
        ),
        migrations.AddIndex(
            model_name='logisticdemo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product_ru'], name='primary_log_search__93d237_gin'),
        ),
        migrations.AddIndex(
            model_name='supplierdemo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product'], name='primary_sup_search__029f7e_gin'),
        ),
        migrations.AddIndex(
            model_name='supplierdemo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product_ru'], name='primary_sup_search__e7d1be_gin'),
        ),
        migrations.AddIndex(
            model_name='technologydemo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product'], name='primary_tec_search__6bad96_gin'),
        ),
        migrations.AddIndex(
            model_name='technologydemo',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product_ru'], name='primary_tec_search__ff5c9c_gin'),
        ),
    ]
