# Generated by Django 5.1 on 2025-07-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_logisticdemo_supplierdemo_technologydemo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticdemo',
            options={'verbose_name': 'Логистика', 'verbose_name_plural': 'Логистика'},
        ),
        migrations.AlterModelOptions(
            name='technologydemo',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
    ]
