# Generated by Django 5.1 on 2025-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='htmltag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
