# Generated by Django 5.1 on 2025-08-15 12:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0005_alter_mainpage_htmltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст блока'),
        ),
    ]
