# Generated by Django 5.1 on 2025-09-18 13:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0006_alter_mainpage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст согласия на обработку персональных данных')),
            ],
            options={
                'verbose_name': 'Согласие на обработку персональных данных',
                'verbose_name_plural': 'Согласие на обработку персональных данных',
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст политики')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
    ]
