# Generated by Django 5.1 on 2025-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0007_consentpage_policypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticdemo',
            name='country',
            field=models.TextField(db_index=True, verbose_name='Страна'),
        ),
    ]
