# Generated by Django 5.1 on 2025-08-16 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('search_count', models.PositiveIntegerField(verbose_name='Число поисков поставщиков')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги, руб.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тарифный план подписки',
                'verbose_name_plural': 'Тарифные планы подписок',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSearchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_count', models.PositiveIntegerField(default=0, verbose_name='Добавленные запросы')),
                ('reduce_count', models.PositiveIntegerField(default=0, verbose_name='Использованные запросы')),
                ('available_count', models.PositiveIntegerField(default=0, verbose_name='Доступные запросы')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_count', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись Подписки',
                'verbose_name_plural': 'Подписка, состояние',
            },
        ),
        migrations.CreateModel(
            name='UserSearchCountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_count', models.PositiveIntegerField(default=0, verbose_name='Добавленные запросы')),
                ('reduce_count', models.PositiveIntegerField(default=0, verbose_name='Использованные запросы')),
                ('section', models.CharField(blank=True, choices=[('goods', 'Товары'), ('technology', 'Технологии'), ('logistics', 'Логистика'), ('payment', 'Оплата')], max_length=20, null=True, verbose_name='Раздел')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запись истории Подписки',
                'verbose_name_plural': 'Подписка, история',
            },
        ),
    ]
