# Generated by Django 5.1 on 2025-08-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_clearing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_clearing.subscriptionrates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True, verbose_name='PaymentId')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='OrderId')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('FORM_SHOWED', 'Форма показана'), ('AUTHORIZING', 'Авторизация'), ('AUTHORIZED', 'Авторизован'), ('CONFIRMING', 'Подтверждение'), ('CONFIRMED', 'Подтверждён'), ('REJECTED', 'Отклонён'), ('REFUNDED', 'Возвращён'), ('DEADLINE_EXPIRED', 'Истёк срок')], default='NEW', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_clearing.subscriptionrates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbank_payments', to=settings.AUTH_USER_MODEL)),
                ('user_search_history_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_clearing.usersearchcounthistory', verbose_name='Запись в истории поисков')),
            ],
            options={
                'verbose_name': 'Платёж Т-Банк',
                'verbose_name_plural': 'Платежи Т-Банк',
                'ordering': ['-created_at'],
            },
        ),
    ]
