# Generated by Django 5.1 on 2025-08-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_clearing', '0002_cart_tbankpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchcounthistory',
            name='section',
            field=models.CharField(blank=True, choices=[('goods', 'Товары'), ('technology', 'Технологии'), ('logistics', 'Логистика'), ('payment', 'Оплата'), ('payment_cancel', 'Отмена платежа')], max_length=20, null=True, verbose_name='Раздел'),
        ),
    ]
