# Generated by Django 5.1 on 2025-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Категорию (отрасль)',
                'verbose_name_plural': 'Категории (отрасли)',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('mode', models.CharField(choices=[('a', 'благоприятный режим'), ('b', 'особый режим')], max_length=2)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(db_index=True, verbose_name='Продукция (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(db_index=True, verbose_name='Продукция (русский)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tn_ved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТН ВЭД')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата цены')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
