# Generated by Django 5.1 on 2025-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('index', models.IntegerField()),
                ('category', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Категорию (отрасль)',
                'verbose_name_plural': 'Категории (отрасли)',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('mode', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(db_index=True, verbose_name='Продукция (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(db_index=True, verbose_name='Продукция (русский)')),
            ],
            options={
                'verbose_name': 'Поставщика',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
