# Generated by Django 5.1 on 2025-05-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='mode',
            field=models.CharField(choices=[('a', 'благоприятный режим'), ('b', 'особый режим')], max_length=2),
        ),
    ]
