# Generated by Django 5.1 on 2025-05-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена'),
        ),
    ]
