# Generated by Django 5.1 on 2025-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код категории'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='country',
            name='mode',
            field=models.CharField(choices=[('a', 'благоприятный режим'), ('b', 'особый режим')], max_length=2, verbose_name='Режим ВЭД'),
        ),
    ]
