# Generated by Django 5.1 on 2025-05-29 15:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_category_category_alter_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='search_vector_product',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='search_vector_product_ru',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product_ru'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='test@test.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.TextField(verbose_name='Продукция (английский)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product_ru',
            field=models.TextField(verbose_name='Продукция (русский)'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product'], name='supplier_su_search__303c44_gin'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product_ru'], name='supplier_su_search__a684ec_gin'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            CREATE EXTENSION IF NOT EXISTS unaccent;
            """,
            reverse_sql="""
            DROP EXTENSION IF EXISTS pg_trgm;
            DROP EXTENSION IF EXISTS unaccent;
            """,
        ),
    ]
