# Generated by Django 5.1 on 2025-07-30 11:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_search_vector_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLogistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код категории')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Категорию логистики',
                'verbose_name_plural': 'Категории логистики',
            },
        ),
        migrations.CreateModel(
            name='CategoryTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код категории')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
            ],
            options={
                'verbose_name': 'Категорию технологий',
                'verbose_name_plural': 'Категории технологий',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию продукции', 'verbose_name_plural': 'Категории продукции'},
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(verbose_name='Логистическая услуга (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(verbose_name='Логистическая услуга (русский)')),
                ('email', models.EmailField(max_length=254)),
                ('tn_ved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТН ВЭД')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена')),
                ('price_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата цены')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('search_vector_product', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product')),
                ('search_vector_product_ru', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product_ru')),
            ],
            options={
                'verbose_name': 'Логистика',
                'verbose_name_plural': 'Логистика',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product'], name='supplier_lo_search__fbb121_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product_ru'], name='supplier_lo_search__dccb8e_gin')],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(db_index=True, max_length=255, verbose_name='Страна')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание (английский)')),
                ('product', models.TextField(verbose_name='Технология (английский)')),
                ('contact', models.TextField(verbose_name='Контактная информация')),
                ('description_ru', models.TextField(verbose_name='Описание (русский)')),
                ('product_ru', models.TextField(verbose_name='Технология (русский)')),
                ('email', models.EmailField(max_length=254)),
                ('tn_ved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ТН ВЭД')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена')),
                ('price_date', models.DateField(blank=True, help_text='2022-08-01', null=True, verbose_name='Дата цены')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated_date', models.DateField(auto_now=True, null=True, verbose_name='Изменен')),
                ('search_vector_product', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product')),
                ('search_vector_product_ru', django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='product_ru')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product'], name='supplier_te_search__fbc5b1_gin'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector_product_ru'], name='supplier_te_search__cda0ac_gin')],
            },
        ),
    ]
