# Generated by Django 5.1 on 2025-07-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_categorylogistic_categorytechnology_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logistic',
            options={'verbose_name': 'Логистику', 'verbose_name_plural': 'Логистика'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Технологию', 'verbose_name_plural': 'Технологии'},
        ),
    ]
