# Generated by Django 5.1 on 2025-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_logistic_options_alter_technology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='technology',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник данных'),
        ),
    ]
