# Generated by Django 5.1 on 2025-11-17 20:41

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_logistic_data_source_supplier_data_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='country',
            field=models.TextField(db_index=True, verbose_name='Страна'),
        ),
        migrations.AddIndex(
            model_name='logistic',
            index=django.contrib.postgres.indexes.GinIndex(fields=['country'], name='logistic_country_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
