# Generated by Django 5.1 on 2025-07-31 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0006_alter_logistic_options_alter_technology_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('product', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('product', models.CharField(max_length=255, verbose_name='Запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Наименование компании')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Поставщика в выборке',
                'verbose_name_plural': 'Выборка поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SendedEmailSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('product', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
                ('email_base', models.CharField(blank=True, help_text='Email адрес без символа @', max_length=254, verbose_name='Email без @')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('email', models.EmailField(max_length=254, verbose_name='Email поставщика')),
                ('original_mail', models.CharField(help_text="Email, на который был отправлен запрос, без символа '@'", max_length=255, verbose_name='Оригинальный email запроса (без @)')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('date', models.DateTimeField(verbose_name='Дата письма')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_attachments/%Y/%m/%d/', verbose_name='Вложение')),
                ('message_id', models.CharField(blank=True, help_text='Уникальный идентификатор письма', max_length=255, null=True, unique=True, verbose_name='ID сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_responses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ поставщика',
                'verbose_name_plural': 'Ответы поставщиков',
                'indexes': [models.Index(fields=['user', 'original_mail'], name='customer_ac_user_id_bde072_idx'), models.Index(fields=['received_at'], name='customer_ac_receive_8630e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'date', 'product'), name='unique_email_date_product')],
            },
        ),
    ]
