# Generated by Django 5.1 on 2025-06-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0001_initial'),
        ('supplier', '0004_supplier_search_vector_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'verbose_name': 'Поставщика в выборке', 'verbose_name_plural': 'Выборка поставщиков'},
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Наименование компании'),
        ),
    ]
