# Generated by Django 5.1 on 2025-07-31 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0001_initial'),
        ('supplier', '0006_alter_logistic_options_alter_technology_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendedemailsave',
            options={'verbose_name': 'Запрос отправленный', 'verbose_name_plural': 'Запросы отправленные'},
        ),
        migrations.CreateModel(
            name='SearchResultLogistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('product', models.CharField(max_length=255, verbose_name='Запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.logistic', verbose_name='Наименование компании')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Логистика в выборке',
                'verbose_name_plural': 'Выборка Логистики',
            },
        ),
        migrations.CreateModel(
            name='SearchResultTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('product', models.CharField(max_length=255, verbose_name='Запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.technology', verbose_name='Наименование компании')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Технология в выборке',
                'verbose_name_plural': 'Выборка Технологий',
            },
        ),
    ]
