# Generated by Django 5.1 on 2025-07-31 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0002_alter_sendedemailsave_options_searchresultlogistic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsendlist',
            name='section',
            field=models.CharField(default='test', max_length=20, verbose_name='Раздел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendedemailsave',
            name='section',
            field=models.CharField(default=0, max_length=20, verbose_name='Раздел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailsendlist',
            name='email',
            field=models.CharField(max_length=254, verbose_name='На Email'),
        ),
        migrations.AlterField(
            model_name='mailsendlist',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Наименование компании'),
        ),
        migrations.AlterField(
            model_name='mailsendlist',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Предмет запроса'),
        ),
        migrations.AlterField(
            model_name='mailsendlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='sendedemailsave',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='На Email'),
        ),
        migrations.AlterField(
            model_name='sendedemailsave',
            name='message',
            field=models.TextField(verbose_name='Текст запроса'),
        ),
        migrations.AlterField(
            model_name='sendedemailsave',
            name='product',
            field=models.CharField(max_length=255, verbose_name='Предмет запроса'),
        ),
        migrations.AlterField(
            model_name='sendedemailsave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
