# Generated by Django 5.1 on 2025-08-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0003_mailsendlist_section_sendedemailsave_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_count', models.PositiveIntegerField(default=0, verbose_name='Добавленные запросы')),
                ('reduce_count', models.PositiveIntegerField(default=0, verbose_name='Использованные запросы')),
                ('available_count', models.PositiveIntegerField(default=0, verbose_name='Доступные запросы')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearchCountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_count', models.PositiveIntegerField(default=0, verbose_name='Добавленные запросы')),
                ('reduce_count', models.PositiveIntegerField(default=0, verbose_name='Использованные запросы')),
                ('section', models.CharField(blank=True, choices=[('goods', 'Товары'), ('technology', 'Технологии'), ('logistics', 'Логистика')], max_length=20, null=True, verbose_name='Раздел')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
