# Generated by Django 5.1 on 2025-09-12 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0003_mailsendlist_section_sendedemailsave_section_and_more'),
        ('supplier', '0007_logistic_data_source_supplier_data_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchresult',
            unique_together={('user', 'supplier_name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='searchresultlogistic',
            unique_together={('user', 'supplier_name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='searchresulttechnology',
            unique_together={('user', 'supplier_name', 'product')},
        ),
    ]
