# Generated by Django 5.1 on 2025-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0004_sendedemailsave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendedemailsave',
            old_name='subject',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sendedemailsave',
            old_name='sent_at',
            new_name='sended_at',
        ),
        migrations.AlterField(
            model_name='sendedemailsave',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
