# Generated by Django 5.1 on 2025-10-28 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0004_alter_searchresult_unique_together_and_more'),
        ('supplier', '0007_logistic_data_source_supplier_data_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsendlist',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='mailsendlist',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='category',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='country',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresultlogistic',
            name='category',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresultlogistic',
            name='country',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresulttechnology',
            name='category',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresulttechnology',
            name='country',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['user', 'product'], name='customer_ac_user_id_39af42_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['country'], name='customer_ac_country_4b9abc_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['category'], name='customer_ac_categor_ea780d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresultlogistic',
            index=models.Index(fields=['user', 'product'], name='customer_ac_user_id_4d4ede_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresultlogistic',
            index=models.Index(fields=['country'], name='customer_ac_country_b37f83_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresultlogistic',
            index=models.Index(fields=['category'], name='customer_ac_categor_51ab40_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresulttechnology',
            index=models.Index(fields=['user', 'product'], name='customer_ac_user_id_312010_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresulttechnology',
            index=models.Index(fields=['country'], name='customer_ac_country_66b693_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresulttechnology',
            index=models.Index(fields=['category'], name='customer_ac_categor_d376d5_idx'),
        ),
    ]
