# Generated by Django 5.1 on 2025-11-04 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0005_mailsendlist_category_mailsendlist_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsendlist',
            options={'verbose_name': 'Выборку для отправки Email', 'verbose_name_plural': 'Выборки для отправки Email'},
        ),
        migrations.AlterModelOptions(
            name='sendedemailsave',
            options={'verbose_name': 'Запрос поставщику отправленный', 'verbose_name_plural': 'Запросы поставщикам отправленные'},
        ),
        migrations.AlterUniqueTogether(
            name='mailsendlist',
            unique_together={('user', 'email', 'product', 'section')},
        ),
        migrations.AddIndex(
            model_name='mailsendlist',
            index=models.Index(fields=['user'], name='customer_ac_user_id_bfd8f5_idx'),
        ),
    ]
