# Generated by Django 5.1 on 2025-11-17 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0006_alter_mailsendlist_options_and_more'),
        ('supplier', '0008_alter_logistic_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchresulttechnology',
            unique_together={('user', 'supplier_name', 'country', 'product')},
        ),
        migrations.AddIndex(
            model_name='searchresulttechnology',
            index=models.Index(fields=['user', 'supplier_name', 'country', 'product'], name='customer_ac_user_id_a7a1c2_idx'),
        ),
    ]
