# Generated by Django 5.1 on 2025-11-17 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0007_alter_searchresulttechnology_unique_together_and_more'),
        ('supplier', '0008_alter_logistic_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchresultlogistic',
            unique_together={('user', 'supplier_name', 'country', 'product')},
        ),
    ]
